# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import chat_service_pb2 as chat__service__pb2


class ChatServiceStub(object):
    """Chat service for AI interactions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
                '/ai.chat.v1.ChatService/StreamChat',
                request_serializer=chat__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ChatResponse.FromString,
                )
        self.GetChatHistory = channel.unary_unary(
                '/ai.chat.v1.ChatService/GetChatHistory',
                request_serializer=chat__service__pb2.ChatHistoryRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ChatHistoryResponse.FromString,
                )


class ChatServiceServicer(object):
    """Chat service for AI interactions
    """

    def StreamChat(self, request, context):
        """Stream chat with AI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Get chat history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=chat__service__pb2.ChatRequest.FromString,
                    response_serializer=chat__service__pb2.ChatResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=chat__service__pb2.ChatHistoryRequest.FromString,
                    response_serializer=chat__service__pb2.ChatHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.chat.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Chat service for AI interactions
    """

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ai.chat.v1.ChatService/StreamChat',
            chat__service__pb2.ChatRequest.SerializeToString,
            chat__service__pb2.ChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.chat.v1.ChatService/GetChatHistory',
            chat__service__pb2.ChatHistoryRequest.SerializeToString,
            chat__service__pb2.ChatHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
