// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Mock implementation for development

package chatpb

import (
	"context"
	"google.golang.org/grpc"
)

// ChatServiceClient is the client API for ChatService service.
type ChatServiceClient interface {
	StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (ChatService_StreamChatClient, error)
	GetChatHistory(ctx context.Context, in *ChatHistoryRequest, opts ...grpc.CallOption) (*ChatHistoryResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (ChatService_StreamChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], "/ai.chat.v1.ChatService/StreamChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceStreamChatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_StreamChatClient interface {
	Recv() (*ChatResponse, error)
	grpc.ClientStream
}

type chatServiceStreamChatClient struct {
	grpc.ClientStream
}

func (x *chatServiceStreamChatClient) Recv() (*ChatResponse, error) {
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) GetChatHistory(ctx context.Context, in *ChatHistoryRequest, opts ...grpc.CallOption) (*ChatHistoryResponse, error) {
	out := new(ChatHistoryResponse)
	err := c.cc.Invoke(ctx, "/ai.chat.v1.ChatService/GetChatHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	StreamChat(*ChatRequest, ChatService_StreamChatServer) error
	GetChatHistory(context.Context, *ChatHistoryRequest) (*ChatHistoryResponse, error)
}

type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) StreamChat(*ChatRequest, ChatService_StreamChatServer) error {
	return nil
}

func (UnimplementedChatServiceServer) GetChatHistory(context.Context, *ChatHistoryRequest) (*ChatHistoryResponse, error) {
	return nil, nil
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

type ChatService_StreamChatServer interface {
	Send(*ChatResponse) error
	grpc.ServerStream
}

type chatServiceStreamChatServer struct {
	grpc.ServerStream
}

func (x *chatServiceStreamChatServer) Send(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.chat.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChatHistory",
			Handler:    nil,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       nil,
			ServerStreams: true,
		},
	},
	Metadata: "chat_service.proto",
}
